### ISSUE TITLE
OLEDのライブラリでPILがないと怒られる

### ISSUE THREAD

**Issue by iamsmith06** [iamsmith06/raspi-audio#2]
# 概要

* PILを使いたいがpillowを入れようとしても通らない

```
smith@volumio:~/raspi-audio$ pipenv install pillow
Installing pillow...
Error:  An error occurred while installing pillow!
Error text: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pillow
  Downloading Pillow-9.0.0.tar.gz (49.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py): started
  Building wheel for pillow (setup.py): finished with status 'error'
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow
    Running setup.py install for pillow: started
    Running setup.py install for pillow: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rt1c4sre
       cwd: /tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.10
  creating build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/features.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/_version.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.10/PIL
  running egg_info
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.clang-format'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 989, in <module>
      setup(
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 804, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 1009, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for pillow
    ERROR: Command errored out with exit status 1:
     command: /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-el3aq5ff/install-record.txt --single-version-externally-managed --compile --install-headers /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/include/site/python3.10/pillow
         cwd: /tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/
    Complete output (176 lines):
    running install
    /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.10
    creating build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.10/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.10/PIL
    running egg_info
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.clang-format'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 989, in <module>
        setup(
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 662, in run
        self.run_command('build')
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 804, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py", line 1009, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d7mdkl5t/pillow_aee4aef3efa449609f7a3b1665befddb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-el3aq5ff/install-record.txt --single-version-externally-managed --compile --install-headers /home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/include/site/python3.10/pillow Check the logs for full command output.

✘ Installation Failed 
```

**Comment by iamsmith06** [comment]
対応するパッケージを入れた  
sudo apt-get install libjpeg-dev

なお、PILはpython2で開発が止まっていて、今はpillowを入れて使うものらしい
