### ISSUE TITLE
GPIOの実行にPermissionがないと怒られる

### ISSUE THREAD

**Issue by iamsmith06** [iamsmith06/raspi-audio#3]
権限がないと怒られる

```
smith@volumio:~/raspi-audio$ pipenv run python oled/oled_sample.py
Traceback (most recent call last):
  File "/home/smith/raspi-audio/oled/oled_sample.py", line 18, in <module>
    oled_reset = digitalio.DigitalInOut(board.D4)
  File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/digitalio.py", line 145, in __init__        
    self.direction = Direction.INPUT
  File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/digitalio.py", line 175, in direction       
    self._pin.init(mode=Pin.IN)
  File "/home/smith/.local/share/virtualenvs/raspi-audio-LPBLmFRx/lib/python3.10/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 37, in init
    GPIO.setup(self.id, GPIO.IN)
RuntimeError: No access to /dev/mem.  Try running as root!
```

**Comment by iamsmith06** [comment]
`sudo usermod -aG gpio $USER` 
でGPIOの権限があるグループに入れる

が、i2cするにはさらにグループ追加が必要
`sudo usermod -aG i2c $USER`  
ここまでやってPermissonの問題が解決した
